### ISSUE TITLE
Bug appear on zen version 1.17b

### ISSUE THREAD

**Issue by t4nk3rchu** [ferrocyante/Arc-H#25]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d22ee35e-545e-49bd-8660-0d4fe7d52464" />

As you can see in the photo, there's this weird bug which makes the new extension pop up on new version which makes it keep duplicate the first line in the pop up.

I've tried to disabled all the js, turn off everything in arcline and the problem still persist.
Even if i disabled arcline, it didn't work.

I have to create a new profile and didn't install arcline. That's when everything work fine

**Comment by ferrocyante** [comment]
> <img alt="Image" width="1920" height="1080" src="https://private-user-images.githubusercontent.com/143399475/503988822-d22ee35e-545e-49bd-8660-0d4fe7d52464.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjExMTEwNjQsIm5iZiI6MTc2MTExMDc2NCwicGF0aCI6Ii8xNDMzOTk0NzUvNTAzOTg4ODIyLWQyMmVlMzVlLTU0NWUtNDliZC04NjYwLTBkNGZlN2Q1MjQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyMlQwNTI2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzY2OTk0MmJiNTI2ZTkxYTJjMzBhOWNlNTIzZjRjZjQ5MWY2YjhmNDcwZTgzZjg1ZTZjMjJiMmNlMmFlZTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U2dhk6jw2GZ4xyxjwfaRGdKhSX99O4PW0mwOk3HLRCI">
> As you can see in the photo, there's this weird bug which makes the new extension pop up on new version which makes it keep duplicate the first line in the pop up.
> 
> I've tried to disabled all the js, turn off everything in arcline and the problem still persist. Even if i disabled arcline, it didn't work.
> 
> I have to create a new profile and didn't install arcline. That's when everything work fine

yeah its becuase zen added that extension menu natively i will be removing the one in arcline cause it would be conflicting

**Comment by ferrocyante** [comment]
@t4nk3rchu  you can update it should be fixed for now 
btw i merged panel ui button and toogle compact mode button if left click it will act as toogle compact mode button and if you right click it will open panel

**Comment by ferrocyante** [comment]
https://github.com/user-attachments/assets/dd173dee-16dc-4817-9aed-3e9349a640e9

**Comment by ZenuserZ** [comment]
> 20251023-2009-11.1085503.mp4

I really like the  idea of merged panel ui buttons, its cool, but the extension menu still doesn't work properly :( 

https://github.com/user-attachments/assets/078cec36-082b-4b35-ba3f-c123986c4ef0
